runtime: nodejs22
instance_class: F2
service: default

env_variables:
    MYSQL_HOST: "34.128.92.233"
    MYSQL_USER: "root"
    MYSQL_PASSWORD: "123calobite123"
    MYSQL_DATABASE: "calobite"
    
handlers:
  - url: /.*
    script: auto
